name: CI
on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: taiga-family/actions/setup-node@9b6ebca664f44d0fc34a50bec5f85becdf27d388 # v2.12.0

      - run: |
          if [[ "${{ env.SUPPORT_AUTO_PUSH }}" == "true" ]]; then
              npm run prettier -- --write
              npm run stylelint -- --fix
              npm run lint -- --fix
          else
              npm run prettier -- --check
              npm run stylelint
              npm run lint
          fi

      - run: npx nx run-many -t build --all
      - run: npx nx run-many -t test --all
      - uses: codecov/codecov-action@75cd11691c0faa626561e295848008c8a7dddffe # v5
      - uses: taiga-family/actions/auto-push@9b6ebca664f44d0fc34a50bec5f85becdf27d388 # v2.12.0
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
