name: 🚀 Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.45.2
      - uses: taiga-family/ci/actions/setup/variables@v1.45.2
      - uses: taiga-family/ci/actions/setup/node@v1.45.2
        with:
          node-version: 16.x
      - run: npx nx run demo:build-gh-pages
      - uses: taiga-family/ci/actions/deploy/github-pages@v1.45.2
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
          folder: dist/apps/demo

concurrency:
  group: deploy-${{ github.head_ref }}
  cancel-in-progress: true
