name: Release

env:
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 0
      - uses: taiga-family/ci/actions/setup/node@v1.25.8
      - run: npm run release
        env:
          CI: true
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 0
      - uses: taiga-family/ci/actions/setup/node@v1.25.8
      - run: npx nx run-many --target test --all --coverage --coverageReporters lcov
      - uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: |
            coverage
      - run: echo "::set-output name=projectMatrix::$(npx nx print-affected --target test --select tasks.target.project --all)"
        id: set-project-matrix
      - uses: actions/github-script@v6
        id: parsed-project-matrix
        env:
          PROJECTS: '${{ steps.set-project-matrix.outputs.projectMatrix }}'
        with:
          script: |
            return process.env.PROJECTS.split(',').map(p => './coverage/' + p.trim() + '/lcov.info').join(',');
      - uses: codecov/codecov-action@v3
        with:
          files: ${{ steps.parsed-project-matrix.outputs.result }}
