name: ⚠️ Release

on:
  workflow_dispatch:
    inputs:
      mode:
        type: choice
        description: Bump version as requested
        required: true
        options:
          - minor
          - patch
          - major

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'chore(release)')"
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: taiga-family/ci/actions/run/release-it@v1.111.0
        with:
          ref: ${{ github.ref }}
          mode: ${{ github.event.inputs.mode }}
          npmToken: ${{ secrets.NPM_TOKEN }}
          githubToken: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
